clusters:
- name: gke
  destinationServer: https://34.69.97.35
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

- name: gke
  destinationServer: https://34.72.215.227
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
